In [11]:
import numpy as np
#created a list
list=[1,2,3,4,5,6,7,8,9] 

#Convert list to numpy array
array_1=np.array(list)
array_3=np.array(list).reshape((3,3))
print(array_3)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#sum of rows
row_sum=np.sum(array_3,axis=0)
print(row_sum)

#sum of columns
column_sum=np.sum(array_3,axis=1)
print(column_sum)

#sum of flattened



[12 15 18]
[ 6 15 24]


In [13]:
#MIN OF ROWS
row_min=np.min(array_3,axis=0)
print(row_min)

#MIN OF columns
column_min=np.min(array_3,axis=1)
print(column_min)

[1 2 3]
[1 4 7]


In [14]:
#MAX OF ROWS
row_max=np.max(array_3,axis=0)
print(row_max)

#MAX OF columns
column_max=np.max(array_3,axis=1)
print(column_max)

[7 8 9]
[3 6 9]


In [ ]:
#MAX OF ROWS
row_max=np.max(array_3,axis=0)
print(row_max)

#MAX OF columns
column_max=np.max(array_3,axis=1)
print(column_max)